#ifndef C_V2_TYPES_MQH
#define C_V2_TYPES_MQH

enum ENUM_V2_STATE
{
   V2_STATE_IDLE = 0,
   V2_STATE_SEED_HEDGE,
   V2_STATE_RANGE_GRID,
   V2_STATE_TREND_DE_RISK,
   V2_STATE_FLATTEN,
   V2_STATE_COOLDOWN
};

enum ENUM_V2_ACTION_GROUP
{
   V2_ACTION_NONE = 0,
   V2_ACTION_FLATTEN,
   V2_ACTION_DE_RISK,
   V2_ACTION_EXIT,
   V2_ACTION_ADD
};

#endif
